[package]
name = "dosimeter"
version = "0.1.0"
edition = "2024"
version.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
async-graphql = "7.0.16"
async-graphql-axum = "7.0.17"
kubos-service = { path = "../../../kubos/services/kubos-service" }
tokio = "1.45.1"
axum = "0.8.4"
chrono = "0.4.41"

# I2C communication
linux-embedded-hal = "0.4"
embedded-hal = "1.0.0"